namespace TrackX.Domain.Entities;

public class DynamicsPanama
{
    public string? new_dmcsalidaenlace { get; set; }
    public string? new_dmcsalida { get; set; }
    public string? new_tienlace { get; set; }
    public string? new_ti { get; set; }
    public string? new_dmcentradaenlace { get; set; }
    public string? new_dmcentrada { get; set; }
    public string? new_cartaliberacionnaviera { get; set; }
    public string? new_blnavieraswb { get; set; }
    public string? new_ducatenlace { get; set; }
    public string? new_manifiestoenlace { get; set; }
    public string? new_cartaporte { get; set; }
    public DateTime? new_fecharealizarcertreexportacion { get; set; }
    public DateTime? new_fechadmcsalida { get; set; }
    public DateTime? new_fechacargahubpanama { get; set; }
    public DateTime? new_fechati { get; set; }
    public DateTime? new_fechadmcentrada { get; set; }
    public bool? new_pagonavierarealizado { get; set; }
    public DateTime? new_fechallegadacrc { get; set; }
    public DateTime? new_fechasalidapty { get; set; }
    public string? new_ultimodialibrecontenedor { get; set; }
    public string? new_decertificadodereexportacion { get; set; }
    public string? new_contenedor { get; set; }
    public string? new_factura { get; set; }
    public bool? new_aplicacertificadodeorigen { get; set; }
    public bool? new_aplicacertificadoreexportacion { get; set; }
    public string? new_bloriginal { get; set; }
    public string? new_borradordecertificadodeorigen { get; set; }
    public int? new_cantequipo { get; set; }
    public string? new_cartadesglosecargos { get; set; }
    public string? new_cartatrazabilidad { get; set; }
    public string? new_certificadoorigen { get; set; }
    public string? new_certificadoreexportacion { get; set; }
    public string? _customerid_value { get; set; }
    public string? new_commodity { get; set; }
    public string? new_contidadbultos { get; set; }
    public string? new_draftbl { get; set; }
    public DateTime? new_entregabloriginal { get; set; }
    public object? new_entregacartatrazabilidad { get; set; }
    public DateTime? new_entregatraduccion { get; set; }
    public DateTime? new_eta { get; set; }
    public bool? new_exoneracion { get; set; }
    public string? new_facturacomercial { get; set; }
    public DateTime? new_fechablimpreso { get; set; }
    public DateTime? new_liberacionmovimientoinventario { get; set; }
    public DateTime? new_fechaliberacionfinanciera { get; set; }
    public DateTime? new_fechastatus { get; set; }
    public string? new_bcf { get; set; }
    public string? new_listadeempaque { get; set; }
    public string? new_peso { get; set; }
    public string? new_po { get; set; }
    public string? new_poe { get; set; }
    public string? new_pol { get; set; }
    public string? new_preestado2 { get; set; }
    public string? new_statuscliente { get; set; }
    public string? new_tamaoequipo { get; set; }
    public string? new_traducciondefacturas { get; set; }
    public DateTime? new_actualizacionovernight { get; set; }
    public string? new_comentariosovernight { get; set; }
    public string? title { get; set; }
}
